export const OBJECT_TYPES = {
    OBJECT_3D: 'OBJECT_3D',
    RAPIER_COLLIDER: 'RAPIER_COLLIDER',
    RAPIER_RIGID_BODY: 'RAPIER_RIGID_BODY',
    POINTER_LOCK_CONTROLS: 'POINTER_LOCK_CONTROLS',
    ORBIT_CONTROLS: 'ORBIT_CONTROLS'
}